function show_rest_screen(scr, cfg, blockNum, nBlocks)
%SHOW_REST_SCREEN  Display between-block rest screen; wait for SPACE.
%
%   show_rest_screen(scr, cfg, blockNum, nBlocks)

Screen('FillRect', scr.win, scr.black);
restText = sprintf( ...
    ['Rest Break\n\n' ...
     'Completed  %d  of  %d  blocks.\n\n' ...
     'Take a short break.\n\n' ...
     'Press SPACE when ready to continue.'], ...
    blockNum, nBlocks);
DrawFormattedText(scr.win, restText, 'center', 'center', scr.white, 60);
Screen('Flip', scr.win);
wait_for_key(cfg.keys.space);
end
