function show_instructions(scr, cfg)
%SHOW_INSTRUCTIONS  Display full task instructions and wait for SPACE.
%
%   show_instructions(scr, cfg)

instrText = [ ...
    'GAMBLING TASK\n\n' ...
    'On each trial, choose between:\n\n' ...
    '  SAFE BET:  Always wins $10\n\n' ...
    '  GAMBLE:    Wins $15-$30, but not guaranteed\n\n' ...
    'The gamble win probability is shown as a number (0-9).\n' ...
    'A second number is revealed after your choice.\n' ...
    'You WIN the gamble if the second number is GREATER than the first.\n\n' ...
    'Example: First number = 3\n' ...
    '  Second number 4-9 = WIN      Second number 0-3 = LOSS\n\n' ...
    'Use LEFT / RIGHT arrow keys to choose.\n\n' ...
    'Try to earn as much money as possible!\n\n' ...
    'Press SPACE to begin practice.'];

Screen('FillRect', scr.win, scr.black);
DrawFormattedText(scr.win, instrText, 'center', 'center', scr.white);
Screen('Flip', scr.win);
wait_for_key(cfg.keys.space);
end
