function trialData = init_trial_data(totalTrials, subjectID, sessionNum, blockSeq)
%INIT_TRIAL_DATA  Preallocate the trial data struct.
%
%   trialData = init_trial_data(totalTrials, subjectID, sessionNum, blockSeq)

trialData.subjectID     = subjectID;
trialData.sessionNum    = sessionNum;
trialData.randomSeed    = rng;
trialData.blockSequence = blockSeq;

fields = { ...
    'trialNum', 'blockNum', 'blockType', ...
    'winProbCue', 'gambleAmount', 'safeLeft', ...
    'choice', 'RT', ...
    'outcomeFirstNum', 'outcomeSecondNum', ...
    'gambleWon', 'rewardEarned', ...
    'streakLength', 'isStreakEnforced', ...
    'lostChase', 'missedResponse', ...
    'flipTime_fixation', 'flipTime_gamePresent', ...
    'flipTime_decision', 'flipTime_outcome'};

for f = 1:length(fields)
    trialData.(fields{f}) = nan(totalTrials, 1);
end
end
